// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@3.0.4";

// src/lib/mcp/tools/get-my-profile.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@3.0.4";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.58.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/get-my-profile.ts
var get_my_profile_default = defineTool({
  name: "get_my_profile",
  title: "Get my profile",
  description: "Get the signed-in user's Triviabees profile, referral code and Cash Wallet balance.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_args, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const sb = supabaseForUser(ctx);
    const uid = ctx.getUserId();
    const [{ data: profile, error }, { data: wallet }] = await Promise.all([
      sb.from("profiles").select("full_name, referral_code").eq("id", uid).maybeSingle(),
      sb.from("cash_wallets").select("balance").eq("user_id", uid).maybeSingle()
    ]);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const result = {
      full_name: profile?.full_name ?? null,
      referral_code: profile?.referral_code ?? null,
      cash_wallet_balance: Number(wallet?.balance ?? 0)
    };
    return { content: [{ type: "text", text: JSON.stringify(result) }], structuredContent: { profile: result } };
  }
});

// src/lib/mcp/tools/list-my-orders.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@3.0.4";
import { z } from "npm:zod@^4.6.5";
var list_my_orders_default = defineTool2({
  name: "list_my_orders",
  title: "List my orders",
  description: "List the signed-in user's most recent shop orders with status and total.",
  inputSchema: { limit: z.number().int().min(1).max(50).default(10).describe("How many orders to return.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await supabaseForUser(ctx).from("orders").select("id, status, total_amount, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const orders = (data ?? []).map((o) => ({
      id: String(o.id),
      status: String(o.status ?? ""),
      total: Number(o.total_amount ?? 0),
      created_at: String(o.created_at)
    }));
    return { content: [{ type: "text", text: JSON.stringify(orders) }], structuredContent: { orders } };
  }
});

// src/lib/mcp/tools/list-live-streams.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@3.0.4";
var list_live_streams_default = defineTool3({
  name: "list_live_streams",
  title: "List live selling streams",
  description: "List sellers who are live selling on Triviabees right now.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_args, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await supabaseForUser(ctx).from("live_streams").select("id, title, viewer_count, started_at").eq("status", "live").order("started_at", { ascending: false }).limit(20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const streams = (data ?? []).map((s) => ({
      id: String(s.id),
      title: String(s.title ?? ""),
      viewers: Number(s.viewer_count ?? 0),
      url: `https://triviabees.com/live?id=${s.id}`
    }));
    return { content: [{ type: "text", text: JSON.stringify(streams) }], structuredContent: { streams } };
  }
});

// src/lib/mcp/index.ts
var projectRef = "pcsancednuywpxvuruqb";
var mcp_default = defineMcp({
  name: "triviabees",
  title: "triviabees",
  version: "0.1.0",
  instructions: "Tools for Triviabees. Use get_my_profile for the user's profile and wallet, list_my_orders for their orders, and list_live_streams to see who is live selling now.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_my_profile_default, list_my_orders_default, list_live_streams_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@3.0.4/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
